spring.application.name=cinemora
######################################################    SERVER PORT   ################################################
server.port=9999
######################################################     MINIO       #################################################
minio.endpoint=http://localhost:9001
minio.accessKey=SlAgbSA01Thtwgv7KGar
minio.secretKey=taqfGxlbmmyanfhff9PNDV2lh2IW3i5MpZsdz9n1
project.upload.path.default-bucket=bexa-default
delete.default-bucket=deleted-default
archived.default-bucket=archived-default
############################################       Multipart Properties     ############################################
# Whether to enable support of multipart uploads.
spring.servlet.multipart.enabled=true
# Threshold after which files are written to disk.
spring.servlet.multipart.file-size-threshold=2KB
# Max file size.
spring.servlet.multipart.max-file-size=1GB
# Max request size.
spring.servlet.multipart.max-request-size=1GB
# Whether to resolve the multipart request lazily at the time of file or parameter access.
spring.servlet.multipart.resolve-lazily=false
