spring.application.name=cinemora
######################################################    SERVER PORT   ################################################
server.port=7777
######################################################     MINIO       #################################################
minio.endpoint=${MINIO_URL:http://localhost:9000}
minio.accessKey=${MINIO_ACCESS_KEY:minioadmin}
minio.secretKey=${MINIO_SECRET_KEY:minioadmin123}
project.upload.path.default-bucket=bexa-default
#delete.default-bucket=deleted-default
#archived.default-bucket=archived-default
root.path=home/files/
project.upload.path.format={YYYY}/{MM}/{DD}/
############################################       Multipart Properties     ############################################
spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=2KB
spring.servlet.multipart.max-file-size=1GB
spring.servlet.multipart.max-request-size=1GB
spring.servlet.multipart.resolve-lazily=false
######################################################    DATABASE     #################################################
spring.sql.init.platform=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.url=${SPRING_DATASOURCE_URL}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.url=jdbc:postgresql://localhost:5432/cinemora_db
spring.datasource.username=postgres
spring.datasource.password=bexa
spring.jpa.hibernate.ddl-auto=update